import { chromium } from '@playwright/test'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport:{width:390,height:800}, hasTouch:true, isMobile:true })
const p = await ctx.newPage()
const errs=[]
p.on('console', m=>{ if(m.type()==='error') errs.push('CONSOLE: '+m.text()) })
p.on('pageerror', e=>errs.push('PAGEERROR: '+e.message))
await p.goto('http://localhost:4180/', { waitUntil:'load' }); await p.waitForTimeout(2500)
// try the home CTA (View projects -> RouterLink)
const cta = p.getByRole('link', { name: /view projects/i })
console.log('CTA exists:', await cta.count(), '| href:', await cta.first().getAttribute('href').catch(()=>'n/a'))
await cta.first().click().catch(e=>errs.push('CLICK ERR: '+e.message))
await p.waitForTimeout(800)
console.log('after CTA click, path:', new URL(p.url()).pathname)
console.log('=== ERRORS ===', errs.length? errs.slice(0,8) : 'none')
await b.close()
